export const bibleBooks = [
  { id: "Genesis", name: "Gênesis", chapters: 50 },
  { id: "Exodus", name: "Êxodo", chapters: 40 },
  { id: "Leviticus", name: "Levítico", chapters: 27 },
  { id: "Numbers", name: "Números", chapters: 36 },
  { id: "Deuteronomy", name: "Deuteronômio", chapters: 34 },
  { id: "Joshua", name: "Josué", chapters: 24 },
  { id: "Judges", name: "Juízes", chapters: 21 },
  { id: "Ruth", name: "Rute", chapters: 4 },
  { id: "1 Samuel", name: "1 Samuel", chapters: 31 },
  { id: "2 Samuel", name: "2 Samuel", chapters: 24 },
  { id: "1 Kings", name: "1 Reis", chapters: 22 },
  { id: "2 Kings", name: "2 Reis", chapters: 25 },
  { id: "1 Chronicles", name: "1 Crônicas", chapters: 29 },
  { id: "2 Chronicles", name: "2 Crônicas", chapters: 36 },
  { id: "Ezra", name: "Esdras", chapters: 10 },
  { id: "Nehemiah", name: "Neemias", chapters: 13 },
  { id: "Esther", name: "Ester", chapters: 10 },
  { id: "Job", name: "Jó", chapters: 42 },
  { id: "Psalms", name: "Salmos", chapters: 150 },
  { id: "Proverbs", name: "Provérbios", chapters: 31 },
  { id: "Ecclesiastes", name: "Eclesiastes", chapters: 12 },
  { id: "Song of Solomon", name: "Cânticos", chapters: 8 },
  { id: "Isaiah", name: "Isaías", chapters: 66 },
  { id: "Jeremiah", name: "Jeremias", chapters: 52 },
  { id: "Lamentations", name: "Lamentações", chapters: 5 },
  { id: "Ezekiel", name: "Ezequiel", chapters: 48 },
  { id: "Daniel", name: "Daniel", chapters: 12 },
  { id: "Hosea", name: "Oséias", chapters: 14 },
  { id: "Joel", name: "Joel", chapters: 3 },
  { id: "Amos", name: "Amós", chapters: 9 },
  { id: "Obadiah", name: "Obadias", chapters: 1 },
  { id: "Jonah", name: "Jonas", chapters: 4 },
  { id: "Micah", name: "Miquéias", chapters: 7 },
  { id: "Nahum", name: "Naum", chapters: 3 },
  { id: "Habakkuk", name: "Habacuque", chapters: 3 },
  { id: "Zephaniah", name: "Sofonias", chapters: 3 },
  { id: "Haggai", name: "Ageu", chapters: 2 },
  { id: "Zechariah", name: "Zacarias", chapters: 14 },
  { id: "Malachi", name: "Malaquias", chapters: 4 },
  { id: "Matthew", name: "Mateus", chapters: 28 },
  { id: "Mark", name: "Marcos", chapters: 16 },
  { id: "Luke", name: "Lucas", chapters: 24 },
  { id: "John", name: "João", chapters: 21 },
  { id: "Acts", name: "Atos", chapters: 28 },
  { id: "Romans", name: "Romanos", chapters: 16 },
  { id: "1 Corinthians", name: "1 Coríntios", chapters: 16 },
  { id: "2 Corinthians", name: "2 Coríntios", chapters: 13 },
  { id: "Galatians", name: "Gálatas", chapters: 6 },
  { id: "Ephesians", name: "Efésios", chapters: 6 },
  { id: "Philippians", name: "Filipenses", chapters: 4 },
  { id: "Colossians", name: "Colossenses", chapters: 4 },
  { id: "1 Thessalonians", name: "1 Tessalonicenses", chapters: 5 },
  { id: "2 Thessalonians", name: "2 Tessalonicenses", chapters: 3 },
  { id: "1 Timothy", name: "1 Timóteo", chapters: 6 },
  { id: "2 Timothy", name: "2 Timóteo", chapters: 4 },
  { id: "Titus", name: "Tito", chapters: 3 },
  { id: "Philemon", name: "Filemom", chapters: 1 },
  { id: "Hebrews", name: "Hebreus", chapters: 13 },
  { id: "James", name: "Tiago", chapters: 5 },
  { id: "1 Peter", name: "1 Pedro", chapters: 5 },
  { id: "2 Peter", name: "2 Pedro", chapters: 3 },
  { id: "1 John", name: "1 João", chapters: 5 },
  { id: "2 John", name: "2 João", chapters: 1 },
  { id: "3 John", name: "3 João", chapters: 1 },
  { id: "Jude", name: "Judas", chapters: 1 },
  { id: "Revelation", name: "Apocalipse", chapters: 22 }
];
